CREATE DATABASE pgc;

\c pgc;

CREATE SCHEMA ak;

CREATE USER ak WITH PASSWORD 'ak';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ak TO ak;
GRANT USAGE ON SCHEMA ak TO ak;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
